version: "3"
services:
  mysql: 
    image: cualestunombre/back:mysql
    restart: unless-stopped
    container_name: appmysql
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: myapp

  authentication:
    image: cualestunombre/back:authentication
    container_name: app_authentication
    volumes:
      - ./authentication/upload/image:/usr/src/app/authentication/upload/image
    depends_on:
      - mysql  # MySQL 서비스가 먼저 실행되도록 의존성을 추가

  community:
    image: cualestunombre/back:community  # <-- 여기를 수정: cualestunombre/back:community 로 변경
    container_name: app_community
    volumes: 
      - ./community/upload/image:/usr/src/app/community/upload/image
    depends_on:
      - authentication  # Authentication 서비스가 먼저 실행되도록 의존성을 추가

  nginx:
    image: cualestunombre/back:nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - community  # Community 서비스가 먼저 실행되도록 의존성을 추가
