version: "3"
services:
  mysql: 
    image: cualestunombre/back:mysql
    restart: unless-stopped
    container_name: app_mysql
    volumes:
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: myapp

  mongodb:
    image: cualestunombre/back:mongodb
    container_name: app_mongodb

  authentication:
    image: cualestunombre/back:authentication
    container_name: app_authentication
    volumes:
      - ./authentication/upload/image:/usr/src/app/authentication/upload/image
   
  redis:
    image: cualestunombre/back:redis
    container_name: app_redis
    
  

  community:
    image: cualestunombre/back:community 
    container_name: app_community
    volumes: 
      - ./community/upload/image:/usr/src/app/community/upload/image
 
  socket:
    image: cualestunombre/back:socket
    container_name: app_socket


  nginx:
    image: cualestunombre/back:nginx
    container_name: app_nginx
    restart: always # 죽으면 항상 살아 있게 함
    ports:
      - "80:80"
 
