version: "3"
services:
  mysql: 
    image: cualestunombre/back:mysql
    restart: unless-stopped
    container_name: app_mysql
    volumes:
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: myapp
   

  authentication:
    image: cualestunombre/back:authentication
    container_name: app_authentication
    volumes:
      - ./authentication/upload/image:/usr/src/app/authentication/upload/image
   

  

  community:
    image: cualestunombre/back:community 
    container_name: app_community
    volumes: 
      - ./community/upload/image:/usr/src/app/community/upload/image
 

  nginx:
    image: cualestunombre/back:nginx
    container_name: app_nginx
    restart: always # 죽으면 항상 살아 있게 함
    ports:
      - "80:80"
 
