version: "3"
services:
  mysql: 
    image: cualestunombre/local:mysql
    restart: unless-stopped
    container_name: app_mysql
    volumes:
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
      - ./mysql_data:/var/lib/mysql  # MySQL 데이터 디렉토리를 로컬에 저장
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp

  authentication:
    image: cualestunombre/local:authentication
    container_name: app_authentication
    volumes:
      - ./authentication/upload/image:/usr/src/app/authentication/upload/image
    
  redis:
    image: cualestunombre/local:redis
    container_name: app_redis

  mongodb:
    restart: unless-stopped
    image: cualestunombre/local:mongodb
    container_name: app_mongodb
    volumes:
      - ./mongodb_data:/data/db  # MongoDB 데이터 디렉토리를 로컬에 저장

  community:
    image: cualestunombre/local:community 
    container_name: app_community
    volumes: 
      - ./community/upload/image:/usr/src/app/community/upload/image
  
  socket:
    image: cualestunombre/local:socket
    container_name: app_socket

  nginx:
    image: cualestunombre/local:nginx
    container_name: app_nginx
    restart: always # 죽으면 항상 살아 있게 함
    ports:
      - "80:80"
  